fx_version 'cerulean'
game 'gta5'
lua54 'yes'
author 'DPS Development'
description 'Rider tools for the DPS railway: board/disembark + seat mapping'
version '1.0.0'
client_script 'client.lua'
server_script 'server.lua'
