fx_version 'cerulean'
game 'gta5'
lua54 'yes'
author 'DPS Development'
description 'Rider tools for the DPS railway: proximity boarding + seat mapping'
version '1.1.0'
shared_script '@ox_lib/init.lua'
client_script 'client.lua'
server_script 'server.lua'
dependency 'ox_lib'
